version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "soa"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d soa" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - dev
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  first:
    build: first-service/
    command: java -jar ./first-service-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    links:
      - postgres
    networks:
      - dev
    depends_on:
      postgres:
        condition: service_healthy

  second:
    build: second-service/
    ports:
      - "8081:8081"
      - "9990:9990"
    networks:
      - dev

networks:
  dev:
    driver: bridge
